### ISSUE TITLE
Error when trying to run seed or compile in vercel

### ISSUE THREAD

**Issue by thallysondias** [datastax/ragbot-starter#19]
I'm trying to try it, but errors occur when trying to run the run seed... When deploying to vercel, too.

I didn't make any changes to the code, other than the .env

```
> ragbot-starter@0.1.0 seed
> ts-node ./scripts/populateDb.ts

error: https://2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com/api/json/v1/documentation: getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com
error: Data: {
  createCollection: { name: 'chat_cosine', options: { vector: [Object] } }
}
error: Error: Command "createCollection" failed with the following errors: [{"message":"getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com"}]
    at handleIfErrorResponse (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:226:15)
    at HTTPClient.executeCommand (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:205:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/db.ts:78:14
    at async executeOperation (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/utils.ts:173:15)
    at async AstraDB.createCollection (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/client.ts:89:16)
chat_cosine already exists
error: https://2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com/api/json/v1/documentation: getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com
error: Data: {
  createCollection: { name: 'chat_euclidean', options: { vector: [Object] } }
}
error: Error: Command "createCollection" failed with the following errors: [{"message":"getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com"}]
    at handleIfErrorResponse (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:226:15)
    at HTTPClient.executeCommand (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:205:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/db.ts:78:14
    at async executeOperation (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/utils.ts:173:15)
    at async AstraDB.createCollection (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/client.ts:89:16)
chat_euclidean already exists
error: https://2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com/api/json/v1/documentation: getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com
error: Data: {
  createCollection: { name: 'chat_dot_product', options: { vector: [Object] } }
}
error: Error: Command "createCollection" failed with the following errors: [{"message":"getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com"}]
    at handleIfErrorResponse (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:226:15)
    at HTTPClient.executeCommand (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:205:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/db.ts:78:14
    at async executeOperation (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/utils.ts:173:15)
    at async AstraDB.createCollection (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/client.ts:89:16)
chat_dot_product already exists
error: https://2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com/api/json/v1/documentation/chat_euclidean: getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com
error: Data: {
  insertOne: {
    document: {
      document_id: 'https://www.datastax.com/services/support/premium-support/faq-0',
      '$vector': [Array],
      url: 'https://www.datastax.com/services/support/premium-support/faq',
      title: 'FAQ | DataStax Premium Support',
      content: 'What is DataStax Premium Support?\n' +
        'Premium Support consists of three add-on offerings available to enhance your existing DataStax support experience\n' +
        'There are three Premium offerings currently available:\n' +
        'Premium Cloud Engineer\n' +
        'Named Engineer\n' +
        'Technical Account Manager\n' +
        'Can I purchase a Premium Support subscription for any DataStax product? \n' +
        'You can purchase Premium Support as an add-on to DataStax products that are generally available. Please contact PremiumSupport@datastax.com if you have any questions.\n' +
        'What is included in each of the different DataStax technical support offerings?\n' +
        'Please refer to the DataStax \n' +
        'Support Comparison Matrix\n' +
        '.\n' +
        'Can I combine DataStax Premium Support options?\n' +
        'Yes.\n' +
        'You can combine add-on options to meet your business needs. The choice is entirely up to you.\n' +
        'How long is the Premium subscription period?\n' +
        'Typical Premium subscriptions are annual.\n' +
        'If my support needs are different from what you currently offer, what should I do?\n' +
        'Contact \n' +
        'PremiumSupport@datastax.com'
    }
  }
}
error: Error: Command "insertOne" failed with the following errors: [{"message":"getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com"}]
    at handleIfErrorResponse (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:226:15)
    at HTTPClient.executeCommand (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:205:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/collection.ts:132:26
    at async executeOperation (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/utils.ts:173:15)
/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:226
        throw new StargateServerError(response, data);
              ^
StargateServerError: Command "insertOne" failed with the following errors: [{"message":"getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com"}]
    at handleIfErrorResponse (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:226:15)
    at HTTPClient.executeCommand (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/client/httpClient.ts:205:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/collection.ts:132:26
    at async executeOperation (/Users/thallysondias/ragbot-omnibees/node_modules/@datastax/astra-db-ts/src/collections/utils.ts:173:15) {
  errors: [
    {
      message: 'getaddrinfo ENOTFOUND 2d85a574-4821-42d6-b3a4-18355a3e283e-2d85a574-4821-42d6-b3a4-18355a3e283e-1.apps.astra.datastax.com'
    }
  ],
  command: { insertOne: { document: [Object] } },
  status: undefined
}
```

**Comment by mfortman11** [comment]
@thallysondias this looks like an issue w/ your `ASTRA_DB_REGION` variable
You added the region id but all you need is the highlight region name
![Screen Shot 2024-01-24 at 9 33 24 AM](https://github.com/datastax/ragbot-starter/assets/6100513/62005ab8-921f-4d43-b78a-a2a074ffe729)
We'll look to clarify this for users going forward

**Comment by thallysondias** [comment]
thanks! now works
